### ISSUE TITLE
Hermes not usable with Processing 3 in Eclipse

### ISSUE THREAD

**Issue by D3add3d** [rdlester/hermes#9]
Might be related to #6 

    Exception in thread "Animation Thread" java.lang.NoSuchMethodError: processing.core.PApplet.addKeyListener(Ljava/awt/event/KeyListener;)V
	at hermes.postoffice.PostOffice.POInit(Unknown Source)
	at hermes.postoffice.PostOffice.<init>(Unknown Source)
	at hermes.World.<init>(Unknown Source)

The above happens when I try to construct a World.

System info:
- Elementary OS freya 64-bit
- Oracle JDK 1.8.0_74
- Eclipse MARS.2 (4.5.2)

**Comment by rdlester** [comment]
Yes. This is the same bug. I'm closing this as a duplicate; please subscribe to notifications on #6 for updates.
